name: Publish to PyPi

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.9
          uses: actions/setup-python@v2
          with:
              python-version: "3.9"
        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              python -m pip install -r requirements.txt
        - name: Build
          run: |
              python setup.py sdist
              python setup.py bdist_wheel
        - name: Publish
          run: |
              twine upload dist/*
          env:
              TWINE_USERNAME: ${{secrets.PYPI_USERNAME}}
              TWINE_PASSWORD: ${{secrets.PYPI_PASSWORD}}
